### ISSUE TITLE
GKE: auth service LB health check

### ISSUE THREAD

**Issue by viv-4** [place-labs/k8s-helm#59]
23/7/22 master branch: Auth service fails the deployed LB health check of `/`, requires manual editing in GCP console to `/auth/authority?health=true`

Adding probes as below configures the LB health check for auth correctly on creation
However, the container fails the probes and is restarted by kubernetes
Removing the probes from the running deployment and leaving the LB health check as `/auth/authority?health=true` resolves
Not defining probes on deployment/LB creation (current state) results in the container running fine but LB health check failing with  `/` request
Requires further investigation

```
          livenessProbe:
            httpGet:
              path: /auth/authority?health=true
              port: http
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /auth/authority?health=true
              port: http
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
```
